steps:
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk:alpine"
    entrypoint: "bash"
    args: ["./app/build.sh"]
    secretEnv: ["GITHUB_TOKEN"]
availableSecrets:
  secretManager:
    - versionName: projects/1020317645786/secrets/EVFinder-Github-Token/versions/latest
      env: "GITHUB_TOKEN"
options:
  automapSubstitutions: true
  logging: CLOUD_LOGGING_ONLY
