const hyundaiInteriorColors = {
  "YGN": "Gray",
  "NNB": "Black",
  "VKE": "Dark Green",
  "T9Y": "Black",
  "YPK": "Gray",
  "MMH": "Gray",
  "TRY": "Black",
  "UUE": "Beige",
  "REY": "Gray",
  "MMF": "Tan",
}

const hyundaiTransitStatus = {
  'AA': 'At Sea',
  'DS': 'Dealer Stock',
  'IR': 'In Transit',
  'IT': 'In Transit',
  'PA': 'Port Arrival',
  'TN': 'Ready for Shipment',
}

const hyundaiVinDetailMapping = {
  'DI': 'DI',
  'colors': 'colors',
  'MAPPrice': 'Market Adjustment Price',
  'accessories': 'Accessories',
  'cityMpg': 'City MPG',
  'classDesc': 'Class Description',
  'colorDesc': 'Color Description',
  'cylinders': 'Cylinders',
  'dealerCd': 'Dealer Code',
  'doorCd': 'Door Code',
  'drivetrain': 'Drivetrain',
  'drivetrainDesc': 'Drivetrain Description',
  'engineDesc': 'Engine Description',
  'engineDisplacement': 'Engine Displacement',
  'epaClassDesc': 'EPA Class Description',
  'epaEstAvgMpg': 'EPA Estimated Average MPG',
  'extColorDesc': 'External Color Description',
  'freight': 'Freight Charge',
  'fuelDesc': 'Fuel Description',
  'highwayMpg': 'Highway MPG',
  'horsepower': 'Horsepower',
  'intColorDesc': 'Interior Color Description',
  'inventoryStatus': 'Inventory Status',
  'mileage': 'Mileage',
  'modelCd': 'Model Code',
  'modelGroupCd': 'Model Group Code',
  'modelNm': 'Model Number',
  'modelYear': 'Model Year',
  'msrp': 'MSRP',
  'packages': 'Packages',
  'plannedDeliveryDate': 'Planned Delivery Date',
  'rbcSavings': 'RBC Savings',
  'sortableMileage': 'Vehicle Mileage',
  'totalAccessoryPrice': 'Total Accessory Price',
  'totalExtColorPrice': 'Total Exterior Color Price',
  'totalIntColorPrice': 'Total Interior Color Price',
  'totalOptions': 'Total Options Price',
  'totalPackageOptionPrice': 'Total Package Options Price',
  'totalPackagePrice': 'Total Package Price',
  'totalPackages': 'Total Packages',
  'transmissionDesc': 'Transmission Description',
  'trimDesc': 'Trim Description',
  'vin': 'VIN'
}

export {
  hyundaiInteriorColors,
  hyundaiTransitStatus,
  hyundaiVinDetailMapping,
};