repos:
  - repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
    - id: flake8
      additional_dependencies: [flake8-bugbear]
      args: [
        '--max-line-length=88',
        '--select=C,E,F,W,B,B950',
        '--extend-ignore=E203,E501'
      ]

  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        language_version: python3.10
