###
# Workflow which runs a Percy Test for each PR
###

name: Percy Visual Testing
on:
  workflow_dispatch:
  pull_request:
    branches:
    - main
    paths:
      - 'app/**'

jobs:
  run-visual-tests:
    runs-on: ubuntu-latest
    env:
      PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
    steps:
      - name: Wait for GCP Cloud Build to succeed
        uses: fountainhead/action-wait-for-check@v1.1.0
        id: wait-for-build
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: "Build-EVFinder-App-From-PR (evfinder)"
          ref: ${{ github.event.pull_request.head.sha }}
      # - uses: actions/checkout@v3
      # - uses: actions/setup-node@v3
      #   with:
      #     node-version: 16

      # - name: NPM Install Packages
      #   run: npm install

      # - name: Build Application
      #   working-directory: ./app
      #   run: npx vue-cli-service build --mode production

      # - name: Serve Files
      #   uses: Eun/http-server-action@v1
      #   with:
      #     directory: "./app/dist"
      #     port: 8080
      #     index-files: |
      #       ["index.html", "index.htm"]

      - name: Run Cypress Tests with Percy against Development environment
        if: steps.wait-for-build.outputs.conclusion == 'success'
        working-directory: ./app
        run: npx percy exec -- cypress run --env host=https://dev.theevfinder.com

      - name: Upload Screenshots and Video on Failure
        uses: actions/upload-artifact@v3
        # Only trigger if the previous step failed
        if: failure()
        with:
          name: failure-video
          path: |
            app/cypress/videos/
            app/cypress/screenshots/
