###
# Workflow which runs a Percy Test for each PR
###

name: Percy Visual Testing
on:
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  npm-install-and-build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      
      - run: cd ./app
      - run: ls -la
      - run: npm install
      - run: npx vue-cli-service build --mode production
      - run: npx @percy/cli snapshot ./dist/
      
