###
# Workflow which runs a Percy Test for each PR
###

name: Percy Visual Testing
on:
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  npm-install-and-build:
    runs-on: ubuntu-latest
    env:
      PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: NPM Install Packages
        run: npm install
      - name: Build Application
        working-directory: ./app
        run: npx vue-cli-service build --mode production
      - name: Percy Snapshot
        working-directory: ./app
        run: npx @percy/cli snapshot ./dist/
      
